---

- name: "HIGH | WN22-DC-000290 | AUDIT | Windows Server 2022 domain Controller PKI certificates must be issued by the DoD PKI or an approved External Certificate Authority (ECA)."
  block:
      - name: "HIGH | WN22-DC-000290 | AUDIT | Windows Server 2022 domain Controller PKI certificates must be issued by the DoD PKI or an approved External Certificate Authority (ECA). | Message out"
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 domain Controller PKI certificates must be issued by the DoD PKI or an approved External Certificate Authority (ECA)."

      - name: "HIGH | WN22-DC-000290 | AUDIT | Windows Server 2022 domain Controller PKI certificates must be issued by the DoD PKI or an approved External Certificate Authority (ECA). | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000290'
  when:
      - wn22_dc_000290
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - WN22-DC-000290
      - V-254413
      - SRG-OS-000066-GPOS-00034
      - SV-254413r849055_rule
      - CCI-000185
      - high
      - CAT1

# add some task/external variable for approved CAs, check for DoD and how to pull programatically
- name: "HIGH | WN22-DC-000300 | AUDIT | Windows Server 2022 PKI certificates associated with user accounts must be issued by a DoD PKI or an approved External Certificate Authority (ECA)."
  block:
      - name: "HIGH | WN22-DC-000300 | AUDIT | Windows Server 2022 PKI certificates associated with user accounts must be issued by a DoD PKI or an approved External Certificate Authority (ECA). | Message out"
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 PKI certificates associated with user accounts must be issued by a DoD PKI or an approved External Certificate Authority (ECA)."

      - name: "HIGH | WN22-DC-000300 | AUDIT | Windows Server 2022 PKI certificates associated with user accounts must be issued by a DoD PKI or an approved External Certificate Authority (ECA). | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000300'
  when:
      - wn22_dc_000300
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - WN22-DC-000300
      - V-254414
      - SRG-OS-000066-GPOS-00034
      - SV-254414r849058_rule
      - CCI-000185
      - high
      - CAT1

- name: "HIGH | WN22-AC-000090 | PATCH | Windows Server 2022 reversible password encryption must be disabled."
  community.windows.win_security_policy:
      section: System Access
      key: ClearTextPassword
      value: "0"
  when:
      - wn22_ac_000090
  tags:
      - WN22-AC-000090
      - V-254293
      - SRG-OS-000073-GPOS-00041
      - SV-254293r877397_rule
      - CCI-000226
      - high
      - CAT1

- name: "HIGH | WN22-SO-000300 | PATCH | Windows Server 2022 must be configured to prevent the storage of the LAN Manager hash of passwords."
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      value: NoLMHash
      data: 1
      datatype: dword
  when:
      - wn22_so_000300
  tags:
      - WN22-SO-000300
      - V-254474
      - SRG-OS-000073-GPOS-00041
      - SV-254474r877397_rule
      - CCI-000226
      - high
      - CAT1

- name: "HIGH | WN22-00-000130 | AUDIT | Windows Server 2022 local volumes must use a format that supports NTFS attributes."
  block:
      - name: "HIGH | WN22-00-000130 | AUDIT | Windows Server 2022 local volumes must use a format that supports NTFS attributes."
        ansible.windows.win_shell: Get-Volume
        changed_when: false
        failed_when: false
        check_mode: false
        register: wn22_00_000130_audit

      - name: "HIGH | WN22-00-000130 | AUDIT | Windows Server 2022 local volumes must use a format that supports NTFS attributes. | Message out"
        debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 local volumes must use a format that supports NTFS attributes."

      - name: "HIGH | WN22-00-000130 | AUDIT | Windows Server 2022 local volumes must use a format that supports NTFS attributes. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-00-000130'
  when:
      - wn22_00_000130
  tags:
      - WN22-00-000130
      - V-205663
      - SRG-OS-000080-GPOS-00048
      - SV-254250r848566_rule
      - CCI-000213
      - high
      - CAT1

- name: "HIGH | WN22-CC-000470 | PATCH | Windows Server 2022 Windows Remote Management (WinRM) client must not use Basic authentication."
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client
      value: AllowBasic
      data: 0
      datatype: dword
  when:
      - wn22_cc_000470
      - not win2022stig_skip_for_test
  tags:
      - WN22-CC-000470
      - V-254378
      - SRG-OS-000125-GPOS-00065
      - SV-254378r877395_rule
      - CCI-000877
      - high
      - CAT1

- name: "HIGH | WN22-CC-000500 | PATCH | Windows Server 2022 Windows Remote Management (WinRM) service must not use Basic authentication."
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service
      value: AllowBasic
      data: 0
      datatype: dword
  when:
      - wn22_cc_000500
      - not win2022stig_skip_for_test
  tags:
      - WN22-CC-000500
      - V-254381
      - SRG-OS-000125-GPOS-00065
      - SV-254381r877395_rule
      - CCI-000877
      - high
      - CAT1

- name: "HIGH | WN22-SO-000230 | PATCH | Windows Server 2022 must not allow anonymous enumeration of shares."
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      value: RestrictAnonymous
      data: 1
      datatype: dword
  when:
      - wn22_so_000230
  tags:
      - WN22-SO-000230
      - V-254467
      - SRG-OS-000138-GPOS-00069
      - SV-254467r849217_rule
      - CCI-001090
      - high
      - CAT1

- name: "HIGH | WN22-SO-000250 | PATCH | Windows Server 2022 must restrict anonymous access to Named Pipes and Shares."
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
      value: restrictnullsessaccess
      data: 1
      datatype: dword
  when:
      - wn22_so_000250
  tags:
      - WN22-SO-000250
      - V-254469
      - SRG-OS-000138-GPOS-00069
      - SV-254469r849223_rule
      - CCI-001090
      - high
      - CAT1

- name: "HIGH | WN22-DC-000010 | AUDIT | Windows Server 2022 must only allow administrators responsible for the domain controller to have Administrator rights on the system."
  block:
      - name: "HIGH | WN22-DC-000010 | AUDIT | Windows Server 2022 must only allow administrators responsible for the domain controller to have Administrator rights on the system."
        ansible.windows.win_shell: get-localgroupmember administrators | Select name | Format-Table -HideTableHeaders
        changed_when: false
        failed_when: false
        register: wn22_dc_000010_admin_usrs

      - name: "HIGH | WN22-DC-000010 | AUDIT | Windows Server 2022 must only allow administrators responsible for the domain controller to have Administrator rights on the system."
        ansible.builtin.debug:
            msg:
                - "Alert! Below are the users in the administrators group. Please review and confirm all users should be in this group"
                - "{{ wn22_dc_000010_admin_usrs.stdout_lines }}"

      - name: "HIGH | WN22-DC-000010 | AUDIT | Windows Server 2022 must only allow administrators responsible for the domain controller to have Administrator rights on the system. | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000010'
  when:
      - wn22_dc_000010
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - WN22-DC-000010
      - V-254385
      - SRG-OS-000324-GPOS-00125
      - SV-254385r877392_rule
      - CCI-002235
      - notest
      - high
      - CAT1

- name: "HIGH | WN22-DC-000070 | AUDIT | Windows Server 2022 permissions on the Active Directory data files must only allow System and Administrators access."
  block:
      - name: "HIGH | WN22-DC-000070 | AUDIT | Windows Server 2022 permissions on the Active Directory data files must only allow System and Administrators access. | Message out"
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 permissions on the Active Directory data files must only allow System and Administrators access."

      - name: "WN22-DC-000070 | AUDIT | Windows Server 2022 permissions on the Active Directory data files must only allow System and Administrators access. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000070'
  when:
      - wn22_dc_000070
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - WN22-DC-000070
      - V-254391
      - SRG-OS-000324-GPOS-00125
      - SV-254391r877392_rule
      - CCI-002235
      - high
      - CAT1

- name: "HIGH | WN22-DC-000080 | AUDIT | Windows Server 2022 Active Directory SYSVOL directory must have the proper access control permissions."
  block:
      - name: "HIGH | WN22-DC-000080 | AUDIT | Windows Server 2022 Active Directory SYSVOL directory must have the proper access control permissions. | Message out"
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 Active Directory SYSVOL directory must have the proper access control permissions."

      - name: "HIGH | WN22-DC-000080 | AUDIT | Windows Server 2022 Active Directory SYSVOL directory must have the proper access control permissions. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000080'
  when:
      - wn22_dc_000080
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - WN22-DC-000080
      - V-254392
      - SRG-OS-000324-GPOS-00125
      - SV-254392r877392_rule
      - CCI-002235
      - high
      - CAT1

- name: "HIGH | WN22-DC-000090 | AUDIT | Windows Server 2022 Active Directory Group Policy objects must have proper access control permissions."
  block:
      - name: "HIGH | WN22-DC-000090 | AUDIT | Windows Server 2022 Active Directory Group Policy objects must have proper access control permissions. | Message out"
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 Active Directory Group Policy objects must have proper access control permissions."

      - name: "HIGH | WN22-DC-000090 | AUDIT | Windows Server 2022 Active Directory Group Policy objects must have proper access control permissions. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000090'
  when:
      - wn22_dc_000090
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - WN22-DC-000090
      - V-205741
      - SRG-OS-000324-GPOS-00125
      - SV-205741r569188_rule
      - CCI-002235
      - high
      - CAT1

- name: "HIGH | WN22-DC-000100 | AUDIT | Windows Server 2022 Active Directory Domain Controllers Organizational Unit (OU) object must have the proper access control permissions."
  block:
      - name: "HIGH | WN22-DC-000100 | AUDIT | Windows Server 2022 Active Directory Domain Controllers Organizational Unit (OU) object must have the proper access control permissions. | Message out"
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 Active Directory Domain Controllers Organizational Unit (OU) object must have the proper access control permissions."

      - name: "HIGH | WN22-DC-000100 | AUDIT | Windows Server 2022 Active Directory Domain Controllers Organizational Unit (OU) object must have the proper access control permissions. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000100'
  when:
      - wn22_dc_000100
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - WN22-DC-000100
      - V-254394
      - SRG-OS-000324-GPOS-00125
      - SV-254394r877392_rule
      - CCI-002235
      - high
      - CAT1

- name: "HIGH | WN22-DC-000110 | AUDIT | Windows Server 2022 organization created Active Directory Organizational Unit (OU) objects must have proper access control permissions."
  block:
      - name: "HIGH | WN22-DC-000110 | AUDIT | Windows Server 2022 organization created Active Directory Organizational Unit (OU) objects must have proper access control permissions. | Message out"
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 organization created Active Directory Organizational Unit (OU) objects must have proper access control permissions."

      - name: "HIGH | WN22-DC-000110 | AUDIT | Windows Server 2022 organization created Active Directory Organizational Unit (OU) objects must have proper access control permissions. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000110'
  when:
      - wn22_dc_000110
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - WN22-DC-000110
      - V-254395
      - SV-254395r877392_rule
      - SRG-OS-000324-GPOS-00125
      - CCI-002235
      - high
      - CAT1

# populate a dictionary/list from customer
- name: "HIGH | WN22-MS-000010 | AUDIT | Windows Server 2022 must only allow Administrators responsible for the member server or standalone or nondomain-joined system to have Administrator rights on the system"
  block:
      - name: "HIGH | WN22-MS-000010 | AUDIT | Windows Server 2022 must only allow Administrators responsible for the member server or standalone or nondomain-joined system to have Administrator rights on the system"
        ansible.windows.win_shell: Get-LocalGroupMember -Name 'Administrators'
        changed_when: false
        check_mode: false
        register: wn22_ms_000010_audit

      - name: "HIGH | WN22-MS-000010 | AUDIT | Windows Server 2022 must only allow Administrators responsible for the member server or standalone or nondomain-joined system to have Administrator rights on the system"
        ansible.builtin.debug:
            msg:
                - The following users or groups have Administrator rights on this system
                - "{{ wn22_ms_000010_audit.stdout.split('\n') }}"
        changed_when: false

      - name: "HIGH | WN22-MS-000010 | AUDIT | Windows Server 2022 must only allow Administrators responsible for the member server or standalone or nondomain-joined system to have Administrator rights on the system | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-MS-000010'
  when:
      - wn22_ms_000010
      - "'controller' not in ansible_windows_domain_role"
  tags:
      - WN22-MS-000010
      - V-254428
      - SRG-OS-000324-GPOS-00125
      - SV-254428r877392_rule
      - CCI-002235
      - audit
      - high
      - CAT1

- name: "HIGH | WN22-UR-000020 | PATCH | Windows Server 2022 Act as part of the operating system user right must not be assigned to any groups or accounts."
  ansible.windows.win_user_right:
      name: SeTcbPrivilege
      users: []
      action: set
  when:
      - wn22_ur_000020
  tags:
      - WN22-UR-000020
      - V-254492
      - SRG-OS-000324-GPOS-00125
      - SV-254492r877392_rule
      - CCI-002235
      - high
      - CAT1

- name: "HIGH | WN22-UR-000060 | PATCH | Windows Server 2022 Create a token object user right must not be assigned to any groups or accounts."
  community.windows.win_security_policy:
      section: Privilege Rights
      key: SeCreateTokenPrivilege
      value: ""
  when:
      - wn22_ur_000060
  tags:
      - WN22-UR-000060
      - V-254496
      - SRG-OS-000324-GPOS-00125
      - SV-254496r877392_rule
      - CCI-002235
      - CAT1

# fails openscap - the v1r10 xml checks for "Administrators" string but secedit uses the SIDs thus
# "SeDebugPrivilege = *S-1-5-32-544"  is Administrators (openscap fails)
# emailed_disa.letterkenny.re.mbx.stig-customer-support-mailbox@mail.mil
# SCC tool works
- name: "HIGH | WN22-UR-000100 | PATCH | Windows Server 2022 Debug programs: user right must only be assigned to the Administrators group."
  ansible.windows.win_user_right:
      name: SeDebugPrivilege
      users: Administrators
      action: set
  when:
      - wn22_ur_000100
  tags:
      - WN22-UR-000100
      - V-254500
      - SRG-OS-000324-GPOS-00125
      - SV-254500r877392_rule
      - CCI-002235
      - high
      - CAT1
