---

# THE FOLLOWING 3 CONTROLS WILL FAIL UNLESS THEY ARE IN THE FOLLOWING ORDER FOR CLOUD BASED SYSTEMS
# The below task is dependent on WN22-AC-000020 and WN22-AC-000030, maybe custom fail when known error if WN22-AC-000020 not set? "The key 'LockoutDuration' in section 'System Access' is not a valid key, cannot set this value"
- name: "MEDIUM | WN22-AC-000020 | PATCH | Windows Server 2022 must have the number of allowed bad logon attempts configured to three or less."
  block:
      - name: "MEDIUM | WN22-AC-000020 | AUDIT | Windows Server 2022 must have the number of allowed bad logon attempts configured to three or less. | Warning For Bad Variable."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid number of days set for wn22stig_lockoutbadcount please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - wn22stig_lockoutbadcount == 0 or wn22stig_lockoutbadcount > 3

      - name: "MEDIUM | WN22-AC-000020 | AUDIT | Windows Server 2022 must have the number of allowed bad logon attempts configured to three or less. | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-AC-000020'
        when:
            - wn22stig_lockoutbadcount == 0 or wn22stig_lockoutbadcount > 3

      - name: "MEDIUM | WN22-AC-000020 | PATCH | Windows Server 2022 must have the number of allowed bad logon attempts configured to three or less. | Apply Variable."
        community.windows.win_security_policy:
            section: System Access
            key: LockoutBadCount
            value: "{{ wn22stig_lockoutbadcount }}"
        when:
            - wn22stig_lockoutbadcount > 0
            - wn22stig_lockoutbadcount <= 3
  when:
      - wn22_ac_000020
  tags:
      - WN22-AC-000020
      - V-254286
      - SRG-OS-000021-GPOS-00005
      - SV-254286r848674_rule
      - CCI-000044
      - CAT2

- name: "MEDIUM | WN22-AC-000010 | PATCH | Windows Server 2022 account lockout duration must be configured to 15 minutes or greater."
  block:
      - name: "MEDIUM | WN22-AC-000010 | AUDIT | Windows Server 2022 account lockout duration must be configured to 15 minutes or greater. | Warning For Bad Variable."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid number of minutes set for wn22stig_lockoutduration please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - wn22stig_lockoutduration < 15
            - wn22stig_lockoutduration > 0

      - name: "MEDIUM | WN22-AC-000010 | AUDIT | Windows Server 2022 account lockout duration must be configured to 15 minutes or greater. | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-AC-000010'
        when:
            - wn22stig_lockoutduration < 15
            - wn22stig_lockoutduration > 0

      - name: "MEDIUM | WN22-AC-000010 | PATCH | Windows Server 2022 account lockout duration must be configured to 15 minutes or greater. | Apply Variable."
        community.windows.win_security_policy:
            section: System Access
            key: LockoutDuration
            value: "{{ wn22stig_lockoutduration }}"
        when:
            - wn22stig_lockoutduration == 0 or wn22stig_lockoutduration >= 15
  when:
      - wn22_ac_000010
  tags:
      - WN22-AC-000010
      - V-254285
      - SRG-OS-000329-GPOS-00128
      - SV-254285r848671_rule
      - CCI-002238
      - CAT2

# The below task is dependent on WN22-AC-000020, maybe custom fail when known error if WN22-AC-000020 not set? "The key 'ResetLockoutCount' in section 'System Access' is not a valid key, cannot set this value"
- name: "MEDIUM | WN22-AC-000030 | PATCH | Windows Server 2022 must have the period of time before the bad logon counter is reset configured to 15 minutes or greater."
  block:
      - name: MEDIUM | WN22-AC-000030 | AUDIT | Windows Server 2022 must have the period of time before the bad logon counter is reset configured to 15 minutes or greater."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid number of days set for wn22stig_resetlockoutcount please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - wn22stig_resetlockoutcount > wn22stig_lockoutduration or wn22stig_resetlockoutcount < 15

      - name: MEDIUM | WN22-AC-000030 | AUDIT | Windows Server 2022 must have the period of time before the bad logon counter is reset configured to 15 minutes or greater. | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-AC-000030'
        when:
            - wn22stig_resetlockoutcount > wn22stig_lockoutduration or wn22stig_resetlockoutcount < 15

      - name: "MEDIUM | WN22-AC-000030 | PATCH | Windows Server 2022 must have the period of time before the bad logon counter is reset configured to 15 minutes or greater. | Apply Variable"
        community.windows.win_security_policy:
            section: System Access
            key: ResetLockoutCount
            value: "{{ wn22stig_resetlockoutcount }}"
        when:
            - wn22stig_resetlockoutcount >= 15
            - wn22stig_resetlockoutcount <= wn22stig_lockoutduration
  when:
      - wn22_ac_000030
  tags:
      - WN22-AC-000030
      - V-254287
      - SRG-OS-000021-GPOS-00005
      - SV-254287r848677_rule
      - CCI-000044
      - CCI-002238
      - CAT2
