---

# tasks file for Windows-2022-STIG
- name: Display Banner
  ansible.builtin.debug:
      msg: "{{ lockdown_banner.split('\n') }}"
  tags:
      - always

- name: Gather distribution info
  ansible.builtin.setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check OS version and family
  ansible.builtin.assert:
      that:
          - ansible_os_family == 'Windows'
          - ansible_distribution | regex_search('(Microsoft Windows Server 2022)')
      success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is the detected operating system."
      fail_msg: "This role can only be run against Windows Server 2022 Editions. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare(win2022stig_min_ansible_version, '>=')
      msg: You must use Ansible {{ win2022stig_min_ansible_version }} or greater
  tags:
      - always

- name: Include the preliminary tasks
  ansible.builtin.import_tasks: prelim.yml
  tags:
      - prelim_tasks
